name: Check input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy service.(test or staging or dev)'
        required: true
        default: 'test'

jobs:
  check:
    if: contains(fromJson('["test", "staging", "dev"]'), github.event.inputs.environment)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Success
        run: echo 'success';
