name: Check input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy service.(test or staging or dev)'
        required: true
        default: 'test'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check
        if: ${{ github.event.inputs.environment != 'test' }}
        run: |
          echo "::error ${{ github.event.inputs.environment }} is invalid. Environment must be 'test' or 'staging' or 'dev'."
          exit 1
      - uses: actions/checkout@v2
      - name: Success
        run: echo 'success';
