name: Check input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy service.(test or staging or dev)'
        required: true
        default: 'test'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Make it fail if invalid input
        if: ${{ contains(contains([ "test", "staging", "dev" ], github.event.inputs.environment), 'false')
        run: exit 1
      - name: Success
        run: echo 'success';
