name: Cron Sample
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Tag name of the git or branch name to deploy.'
        required: true
      environment:
        description: 'Environment'
        required: true
        default: 'test'
env:
  ENV: ${{ github.event.inputs.environment }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo $ENV
