name: Cache EB CLI

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Cache brew
        id: cache-ebcli
        uses: actions/cache@v2
        with:
          path: |
            /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew
            /home/linuxbrew/.linuxbrew/Cellar/aws-elasticbeanstalk
          key: ${{ runner.os }}-ebcli-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: ${{ runner.os }}-ebcli-
      - name: Install EB CLI
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install awsebcli
      - name: EB cli help
        run: |
          ls -al /home/linuxbrew/.linuxbrew/Cellar/aws-elasticbeanstalk/3.19.4/
          ls -al /home/linuxbrew/.linuxbrew/Cellar/aws-elasticbeanstalk/3.19.4/libexec/bin
          brew link aws-elasticbeanstalk
          eb -h
