name: Cache EB CLI

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Cache EB CLI
        id: cache-eb-cli
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Homebrew/awsebcli--*
            ~/.cache/Homebrew/downloads/*--awsebcli-*
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-
      - name: Install EB CLI
        if: steps.cache-eb-cli.outputs.cache-hit != 'true'
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install awsebcli
      - name: EB cli help
        run: eb -h
