name: Cache EB CLI

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - uses: actions/setup-python@master
        with:
          python-version: '3.9'
      - name: Install awsebcli
        run: pip install -U awsebcli
      - name: EB cli
        run: |
          export PATH=$pythonLocation/bin:$PATH
          eb --version
