name: Cache EB CLI

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Cache brew
        id: cache-ebcli
        uses: actions/cache@v2
        with:
          path: /home/linuxbrew/.linuxbrew/Cellar/aws-elasticbeanstalk
          key: ${{ runner.os }}-ebcli-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: ${{ runner.os }}-ebcli-
      - name: Install EB CLI
        if: steps.cache-ebcli.outputs.cache-hit != 'true'
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install awsebcli
      - name: EB cli help
        run: eb -h
