name: Finish release branch
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version. ex)1.0.0'
        required: true
env:
  BRANCH_NAME: release/v${{ github.event.inputs.version }}
  TAG_NAME: v${{ github.event.inputs.version }}
jobs:
  merge_release_branch:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Merge into develop
      run: |
        git checkout ${BRANCH_NAME}
        git checkout develop
        git merge --no-ff ${BRANCH_NAME}
        git push origin develop
        git push origin ${BRANCH_NAME}
    - name: Merge into master
      run: |
        git checkout ${BRANCH_NAME}
        git checkout master
        git merge --no-ff ${BRANCH_NAME}
        git push origin master
        git push origin ${BRANCH_NAME}
    - name: Delete release branch
      run: |
        git branch --delete ${BRANCH_NAME}
        git push origin --delete ${BRANCH_NAME}
  create_tag:
    needs: merge_release_branch
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Create tag 
      run: |
        git tag -a ${TAG_NAME}
        git push origin ${TAG_NAME}
  create_release:
    needs: [merge_release_branch, create_tag]
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create release
      uses: actions/checkout@v2
      with:
        tag_name: ${TAG_NAME}
        body_path: .github/RELEASE_NOTE.md
        draft: true
  
