name: Outputs sample
on:
  workflow_dispatch:
  
jobs:
  buil_variable:
    runs-on: ubunts-latest
    outputs:
      environment: ${{ steps.set-deploy-info.environment }}
      deploy_target: ${{ steps.set-deploy-info.deploy_target }}
    steps:
      - name: Set deploy info
        id: set-deploy-info
        run: |
          echo "::set-output environment=dev"
          echo "::set-output deploy_target=develop"
        shell: bash
  op:
    needs: [buil_variable]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output env
        run: |
          echo ${{ buil_variable.outputs.environment }}
          echo ${{ buil_variable.outputs.deploy_target }}
