name: Outputs sample
on:
  workflow_dispatch:
env:
  ENVIRONMENT: dev
  DEPLOY_TARGET: develop
jobs: 
  op:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set deploy info
        id: set-deploy-info
        run: |
          echo "::set-output name=environment::$ENVIRONMENT"
          echo "::set-output name=deploy_target::$DEPLOY_TARGET"
        shell: bash
      - name: Output env
        run: |
          echo ${{ steps.set-deploy-info.outputs.environment }}
          echo ${{ steps.set-deploy-info.outputs.deploy_target }}
