name: Outputs sample
on:
  workflow_dispatch:
  
jobs:
  op:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build outputs variable
        id: build-variable
        run: |
          echo "::set-output environment=dev"
          echo "::set-output deploy_target=develop"
        shell: bash
      - name: Output env
        run: |
          echo ${{ stepts.build-variable.outputs.environment }}
          echo ${{ stepts.build-variable.outputs.deploy_target }}
