name: Output Sample

on:
  push:
    branches: 
      - feature/output-sample

jobs:
  job1:
    runs-on: ubuntu-20.04
    outputs:
      image_tag: ${{ steps.op.outputs.image_tag }}
    steps:
      - name: Set value
        id: op
        run: |
          echo IMAGE_TAG=$(echo feature/output-sample | sed -e 's|[\\._/]|-|g')-$(echo ${GITHUB_SHA} | cut -c 1-8)
          echo ::set-output name=image_tag::${IMAGE_TAG}
      - name: Output
        run: echo ${{ job1.outputs.image_tag }}
          
  job2:
    needs: [job1]
    runs-on: ubuntu-20.04
    steps:
      - name: Output Test
        run: echo ${{ needs.job1.outputs.image_tag }}
