name: Outputs sample
on:
  workflow_dispatch:
  
jobs:
  build_variable:
    runs-on: ubunts-latest
    outputs:
      environment: ${{ steps.set-deploy-info.outputs.environment }}
      deploy_target: ${{ steps.set-deploy-info.outputs.deploy_target }}
    steps:
      - name: Set deploy info
        id: set-deploy-info
        run: |
          echo "::set-output name=environment::dev"
          echo "::set-output name=deploy_target::develop"
        shell: bash
  op:
    needs: build_variable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output env
        run: |
          echo ${{ build_variable.outputs.environment }}
          echo ${{ build_variable.outputs.deploy_target }}
