name: Outputs sample
on:
  workflow_dispatch:
  
jobs:
  op:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.build-variable.outputs.environment }}
      deploy_target: ${{ steps.build-variable.outputs.deploy_target }}
    steps:
      - uses: actions/checkout@v2
      - name: Build outputs variable
        id: build-variable
        run: |
          echo "::set-output environment=dev"
          echo "::set-output deploy_target=develop"
        shell: bash
      - name: Output env
        run: |
          echo ${{ outputs.environment }}
          echo ${{ outputs.deploy_target }}
